- name: Upload Code Coverage to CodeClimate
  uses: paambaati/codeclimate-action@v5.0.0
  env:
    CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  with:
    coverageCommand: make coverage
    coverageLocations: ${{ github.workspace }}/code/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
# Updated GitHub Actions workflow
