name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Build and run tests
      - name: Build and Test with Gradle
        run: ./gradlew clean build test jacocoTestReport

      # Step 5: Set up Code Climate Test Reporter
      - name: Download Code Climate Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - name: Run Code Climate Test Reporter Before-Build
        run: ./cc-test-reporter before-build

      # Step 6: Format the coverage report
      - name: Format Coverage Report
        run: ./cc-test-reporter format-coverage --input-type jacoco ./build/reports/jacoco/test/jacocoTestReport.xml

      # Step 7: Upload coverage to Code Climate
      - name: Upload Coverage to Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: ./cc-test-reporter upload-coverage
