services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - ./gradlew
      - clean
      - test
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app

